### ISSUE TITLE
Conflicting Application: There is another application running that conflicts with keepkey client

### ISSUE THREAD

**Issue by sabotagebeats** [greatwolf/KKClient#3]
Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by greatwolf** [comment]
Yea sometimes that happens when the app doesn't close down cleanly. Usually unplugging and replugging should fix it or just restart the Extension.

**Comment by sabotagebeats** [comment]
> Yea sometimes that happens when the app doesn't close down cleanly. Usually unplugging and replugging should fix it or just restart the Extension.

I tried this however now it says no keepkey detected.

**Comment by sabotagebeats** [comment]
I can get it to recognize the keepkey in update mode, however then it wants to update to 6.4.0 but i'm on 6.6.0

Keepkey Updater says Keepkey Bootloader 1.1.0 Firmware 6.6.0

**Comment by greatwolf** [comment]
ahh yea, the release 6.6.1 only has firmware profile up to v6.5.1. I added 6.6.0 in the master branch but that commit came after I already released 6.6.1. That's the reason it's not detecting. You can copy the 'background.js' file and replace the existing one with that. Just remember to copy over the cloud api keys at the top of the file.

**Comment by greatwolf** [comment]
FYI, commit 7b22d06 contains the necessary change for firmware 6.6.0. You can also manually edit 'background.js and add that in as an alternative to overwriting the whole file..

**Comment by sabotagebeats** [comment]
I updated this, but still can't see keepkey unless i try to "update" it to 6.4.0

**Comment by greatwolf** [comment]
The only thing I can think of is to check `chrome://extensions` and make sure the 'background page' shows `(inactive)` for KeepKey Client. Just toggling the disable and enable button should do it. Sometimes the `background page` stays active for a while even after closing the client. If that happens changes done to `background.js` won't take effect until it's inactive.

**Comment by sabotagebeats** [comment]
I have done this and deleted and replaced the background.js but still unable to see the keepkey unless I connect it in update mode. I get this error in the chrome extension log
`Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`

**Comment by sabotagebeats** [comment]
If I simulate browser restart I'm able to get a conflicting application error and the following errors in chrome extension log
`window.localStorage is not available in packaged apps. Use chrome.storage.local instead.
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
WebUsb setConfiguration failed
Error setting device configuration.
WebUSB claimInterface failed
Error claiming interface.
Unchecked runtime.lastError: The message port closed before a response was received.`

**Comment by greatwolf** [comment]
Just so we're not missing something simple, nothing else is running that could be interacting with the hardware wallet right? eg. KeepKey Updater isn't running in the background when you're doing this or some other app like electrum etc.

Second thing to check, you mention downgrading to firmware v6.4.0 works. What about [v6.5.1](https://github.com/keepkey/keepkey-firmware/releases/tag/v6.5.1)? Does that work or does it run into the problem as v6.6.0?

In the dev/debug console `_generated_background_page.html` does it show something like

    looking for HID devices...
    []
    looking for WebUsb devices...
    [{"device":0}, "manufacturerName": . . .]

Make sure you have `Info` checked in the logging option `Default levels` otherwise it may not show up. It should be checked by default unless you turned it off at some point.

My device uses bootloader 2.0.0 and but same firmware 6.6.0 as yours. I don't think the bootloader would cause this but I'll try to downgrade it and see if I can reproduce the issue.

**Comment by greatwolf** [comment]
Looks like it's not allowing me to downgrade to an older bootloader version. I also just noticed [bootloader 2.0.0](https://github.com/keepkey/keepkey-firmware/releases/tag/bl_v2.0.0) mentioned something about WebUSB in it's list of features. You could try upgrading to that and see if it helps.

**Comment by greatwolf** [comment]
In case this is still a problem, the one other thing you can try is to turn on `chrome://flags/#new-usb-backend`. This is assuming you're under Windows. I encountered this 'Conflicting Application' issue the other day where replugging wouldn't fix it.

In my case, I already had this option enabled so I disabled, restarted browser, re-enabled it, restart browser second time. That resolved it for me.

**Comment by sabotagebeats** [comment]
I was able to get it to work by force closing chrome and then opening keepkey client while chrome is closed. Then it will recognize the keepkey once.
